[theme]
theme = "semi-native"

[theme.overrides]
idle_fg = "#bbbbbb"
separator_fg = "#aaaaaa"
[icons]

[[block]]
block = "custom"
command = "xkb-switch"
interval = 1 
[[block.click]]
button = "left"
cmd = "xkb-switch -n"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m/%Y %R') "

[[block]]
block = "custom"
command = "cat /etc/hostname"
interval = "once"

[[block]]
block = "custom"
command = 'ip -4 addr show | grep wlp | grep -oP "(?<=inet\s)\d+(\.\d+){3}"'
interval = "once"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon root: $available.eng(w:2) "

[[block]]
block = "custom"
command = "echo CPU $(($(cat /sys/class/thermal/thermal_zone0/temp) / 1000))°C"
interval = 5

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "memory"

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "custom"
command = "~/DotFiles/i3/.config/i3/i3status/battery.sh"
interval = 10

