icons_format = "{icon}"

[theme]
theme = "srcery"

[icons]
icons = "awesome6"
[icons.overrides]
bat = ["|E|", "|_|", "|=|", "|F|"]
bat_charging = "|^| "


[[block]]
block = "keyboard_layout"
driver = "xkbswitch"
interval = 1 
[[block.click]]
button = "left"
cmd = "xkb-switch -n"


[[block]]
block = "custom"
command = 'ip -4 addr show | grep wlp | grep -oP "(?<=inet\s)\d+(\.\d+){3}"'
interval = 30 

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon root: $available.eng(w:2) "

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "backlight"
device = "intel_backlight"

[[block]]
block = "memory"



[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90
icons_format = "{icon}"
[block.icons_overrides]
cpu_boost_on = "ON"
cpu_boost_off = "OFF"


[[block]]
block = "custom"
command = "~/DotFiles/.config/i3/i3status/battery.sh"
interval = 10

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m/%Y %R') "


